"""phase 2 tariffs and holidays

Revision ID: 0002_tariffs
Revises: 0001_foundation
Create Date: 2026-09-29 16:25:13.910098
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types

revision = "0002_tariffs"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("title", sa.Unicode(length=120), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("day", name=op.f("uq_holidays_day")),
    )
    op.create_table(
        "tariff_versions",
        sa.Column("effective_from_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("amounts", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("note", sa.Unicode(length=300), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_versions")),
    )
    with op.batch_alter_table("tariff_versions", schema=None) as batch_op:
        batch_op.create_index("ix_tariff_versions_effective", ["effective_from_utc"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tariff_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_tariff_versions_effective")

    op.drop_table("tariff_versions")
    op.drop_table("holidays")
    # ### end Alembic commands ###
