"""phase 3 gate operations

Revision ID: 0003_gate
Revises: 0002_tariffs
Create Date: 2026-09-29 16:56:59.846502
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = (
    "entry_events",
    "exit_events",
    "payments",
    "adjustments",
    "cancellations",
    "debts",
    "reprints",
    "night_marks",
)


revision = "0003_gate"
down_revision = "0002_tariffs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_sessions",
        sa.Column("night_marked", sa.Boolean(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("flags", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=False),
        sa.Column("ticket_sequence", sa.BigInteger(), nullable=False),
        sa.Column("ticket_no", sa.String(length=24), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("pass_type", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("entry_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("entry_minute", sa.BigInteger(), nullable=False),
        sa.Column("no_plate", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_active_sessions")),
    )
    with op.batch_alter_table("active_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_active_sessions_entry", ["entry_at_utc"], unique=False)
        batch_op.create_index("ix_active_sessions_minute", ["gate_code", "entry_minute"], unique=False)
        batch_op.create_index("ix_active_sessions_plate", ["plate_key"], unique=False)
        batch_op.create_index("ix_active_sessions_ticket", ["gate_code", "ticket_sequence"], unique=False)

    op.create_table(
        "adjustments",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("amount_before", sa.BigInteger(), nullable=False),
        sa.Column("amount_after", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Unicode(length=500), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adjustments")),
    )
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.create_index("ix_adjustments_session", ["session_id"], unique=False)

    op.create_table(
        "cancellations",
        sa.Column("target_table", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Unicode(length=500), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cancellations")),
    )
    with op.batch_alter_table("cancellations", schema=None) as batch_op:
        batch_op.create_index("ix_cancellations_target", ["target_table", "target_id"], unique=False)

    op.create_table(
        "debts",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debts")),
    )
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.create_index("ix_debts_plate", ["plate_key"], unique=False)
        batch_op.create_index("ix_debts_session", ["session_id"], unique=False)

    op.create_table(
        "entry_events",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=False),
        sa.Column("ticket_sequence", sa.BigInteger(), nullable=False),
        sa.Column("ticket_no", sa.String(length=24), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("pass_type", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("entry_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("entry_minute", sa.BigInteger(), nullable=False),
        sa.Column("no_plate", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry_events")),
    )
    with op.batch_alter_table("entry_events", schema=None) as batch_op:
        batch_op.create_index("ix_entry_events_entry", ["entry_at_utc"], unique=False)
        batch_op.create_index("ix_entry_events_plate", ["plate_key"], unique=False)
        batch_op.create_index("ix_entry_events_session", ["session_id"], unique=False)
        batch_op.create_index("ix_entry_events_ticket", ["gate_code", "ticket_sequence"], unique=False)

    op.create_table(
        "exit_events",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=False),
        sa.Column("exit_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_minutes", sa.BigInteger(), nullable=False),
        sa.Column("chargeable_minutes", sa.BigInteger(), nullable=False),
        sa.Column("amount_due", sa.BigInteger(), nullable=False),
        sa.Column("breakdown", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("lost_ticket", sa.Boolean(), nullable=False),
        sa.Column("flags", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exit_events")),
    )
    with op.batch_alter_table("exit_events", schema=None) as batch_op:
        batch_op.create_index("ix_exit_events_exit", ["exit_at_utc"], unique=False)
        batch_op.create_index("ix_exit_events_session", ["session_id"], unique=False)

    op.create_table(
        "gate_sequences",
        sa.Column("gate_code", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("last_sequence", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("gate_code", name=op.f("pk_gate_sequences")),
    )
    op.create_table(
        "night_marks",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("night_of", sa.Date(), nullable=False),
        sa.Column("auto", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_night_marks")),
    )
    with op.batch_alter_table("night_marks", schema=None) as batch_op:
        batch_op.create_index("ix_night_marks_session", ["session_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("debt_id", sa.String(length=36), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("reference", sa.Unicode(length=60), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_created", ["created_at_utc"], unique=False)
        batch_op.create_index("ix_payments_session", ["session_id"], unique=False)

    op.create_table(
        "reprints",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reprints")),
    )
    with op.batch_alter_table("reprints", schema=None) as batch_op:
        batch_op.create_index("ix_reprints_session", ["session_id"], unique=False)

    op.create_table(
        "visits",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("ticket_no", sa.String(length=24), nullable=False),
        sa.Column("gate_in", sa.Integer(), nullable=False),
        sa.Column("gate_out", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("entry_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("exit_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=True),
        sa.Column("total_minutes", sa.BigInteger(), nullable=False),
        sa.Column("amount_due", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lost_ticket", sa.Boolean(), nullable=False),
        sa.Column("no_plate", sa.Boolean(), nullable=False),
        sa.Column("night_count", sa.Integer(), nullable=False),
        sa.Column("flags", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visits")),
    )
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.create_index("ix_visits_entry", ["entry_at_utc"], unique=False)
        batch_op.create_index("ix_visits_exit", ["exit_at_utc"], unique=False)
        batch_op.create_index("ix_visits_plate", ["plate_key"], unique=False)
        batch_op.create_index("ix_visits_session", ["session_id"], unique=True)
        batch_op.create_index("ix_visits_status", ["status"], unique=False)

    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.drop_index("ix_visits_status")
        batch_op.drop_index("ix_visits_session")
        batch_op.drop_index("ix_visits_plate")
        batch_op.drop_index("ix_visits_exit")
        batch_op.drop_index("ix_visits_entry")

    op.drop_table("visits")
    with op.batch_alter_table("reprints", schema=None) as batch_op:
        batch_op.drop_index("ix_reprints_session")

    op.drop_table("reprints")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index("ix_payments_session")
        batch_op.drop_index("ix_payments_created")

    op.drop_table("payments")
    with op.batch_alter_table("night_marks", schema=None) as batch_op:
        batch_op.drop_index("ix_night_marks_session")

    op.drop_table("night_marks")
    op.drop_table("gate_sequences")
    with op.batch_alter_table("exit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_exit_events_session")
        batch_op.drop_index("ix_exit_events_exit")

    op.drop_table("exit_events")
    with op.batch_alter_table("entry_events", schema=None) as batch_op:
        batch_op.drop_index("ix_entry_events_ticket")
        batch_op.drop_index("ix_entry_events_session")
        batch_op.drop_index("ix_entry_events_plate")
        batch_op.drop_index("ix_entry_events_entry")

    op.drop_table("entry_events")
    with op.batch_alter_table("debts", schema=None) as batch_op:
        batch_op.drop_index("ix_debts_session")
        batch_op.drop_index("ix_debts_plate")

    op.drop_table("debts")
    with op.batch_alter_table("cancellations", schema=None) as batch_op:
        batch_op.drop_index("ix_cancellations_target")

    op.drop_table("cancellations")
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.drop_index("ix_adjustments_session")

    op.drop_table("adjustments")
    with op.batch_alter_table("active_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_active_sessions_ticket")
        batch_op.drop_index("ix_active_sessions_plate")
        batch_op.drop_index("ix_active_sessions_minute")
        batch_op.drop_index("ix_active_sessions_entry")

    op.drop_table("active_sessions")
    # ### end Alembic commands ###
