"""phase 4 people shops blocklist

Revision ID: 0004_people
Revises: 0003_gate
Create Date: 2026-09-29 17:49:20.458133
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("wallet_transactions", "subscription_payments", "block_attempts")


revision = "0004_people"
down_revision = "0003_gate"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "block_attempts",
        sa.Column("block_id", sa.String(length=36), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("photo_path", sa.Unicode(length=400), nullable=True),
        sa.Column("details", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_block_attempts")),
    )
    with op.batch_alter_table("block_attempts", schema=None) as batch_op:
        batch_op.create_index("ix_block_attempts_block", ["block_id"], unique=False)

    op.create_table(
        "blocks",
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("person_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Unicode(length=500), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
    )
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.create_index("ix_blocks_person", ["person_id"], unique=False)
        batch_op.create_index("ix_blocks_plate", ["plate_key"], unique=False)

    op.create_table(
        "guest_permits",
        sa.Column("person_id", sa.String(length=36), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("note", sa.Unicode(length=300), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_permits")),
    )
    with op.batch_alter_table("guest_permits", schema=None) as batch_op:
        batch_op.create_index("ix_guest_permits_person", ["person_id"], unique=False)

    op.create_table(
        "people",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("free_category", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.Unicode(length=80), nullable=False),
        sa.Column("last_name", sa.Unicode(length=80), nullable=False),
        sa.Column("mobile", sa.String(length=20), nullable=True),
        sa.Column("shop_id", sa.String(length=36), nullable=True),
        sa.Column("brand", sa.Unicode(length=120), nullable=True),
        sa.Column("location_type", sa.String(length=10), nullable=False),
        sa.Column("vehicle_model", sa.Unicode(length=80), nullable=True),
        sa.Column("notes", sa.Unicode(length=500), nullable=True),
        sa.Column("payer", sa.String(length=10), nullable=False),
        sa.Column("price_override", sa.BigInteger(), nullable=True),
        sa.Column("max_concurrent", sa.Integer(), nullable=False),
        sa.Column("subscription_end_utc", caspian_parking.data.types.UTCDateTime(), nullable=True),
        sa.Column("negative_allowed", sa.Boolean(), nullable=False),
        sa.Column("negative_max_days", sa.Integer(), nullable=False),
        sa.Column("negative_approved_by", sa.String(length=36), nullable=True),
        sa.Column("night_exempt", sa.Boolean(), nullable=False),
        sa.Column("night_exempt_approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_index("ix_people_kind", ["kind"], unique=False)
        batch_op.create_index("ix_people_shop", ["shop_id"], unique=False)

    op.create_table(
        "person_plates",
        sa.Column("person_id", sa.String(length=36), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=False),
        sa.Column("description", sa.Unicode(length=120), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_plates")),
    )
    with op.batch_alter_table("person_plates", schema=None) as batch_op:
        batch_op.create_index("ix_person_plates_person", ["person_id"], unique=False)
        batch_op.create_index("ix_person_plates_plate", ["plate_key"], unique=False)

    op.create_table(
        "shops",
        sa.Column("name", sa.Unicode(length=120), nullable=False),
        sa.Column("location_type", sa.String(length=10), nullable=False),
        sa.Column("unit", sa.Unicode(length=120), nullable=True),
        sa.Column("phone", sa.Unicode(length=30), nullable=True),
        sa.Column("contact_name", sa.Unicode(length=120), nullable=True),
        sa.Column("notes", sa.Unicode(length=500), nullable=True),
        sa.Column("low_balance_threshold", sa.BigInteger(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
    )
    op.create_table(
        "subscription_payments",
        sa.Column("person_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("shop_id", sa.String(length=36), nullable=True),
        sa.Column("paid_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("previous_end_utc", caspian_parking.data.types.UTCDateTime(), nullable=True),
        sa.Column("new_end_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("used_days", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_payments")),
    )
    with op.batch_alter_table("subscription_payments", schema=None) as batch_op:
        batch_op.create_index("ix_subscription_payments_person", ["person_id", "paid_at_utc"], unique=False)

    op.create_table(
        "wallet_transactions",
        sa.Column("shop_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=True),
        sa.Column("person_id", sa.String(length=36), nullable=True),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Unicode(length=300), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_transactions")),
    )
    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.create_index("ix_wallet_transactions_shop", ["shop_id", "created_at_utc"], unique=False)

    with op.batch_alter_table("active_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("person_id", sa.String(length=36), nullable=True))
        batch_op.create_index("ix_active_sessions_person", ["person_id"], unique=False)

    with op.batch_alter_table("entry_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("person_id", sa.String(length=36), nullable=True))
        batch_op.create_index("ix_entry_events_person", ["person_id", "entry_at_utc"], unique=False)

    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("person_id", sa.String(length=36), nullable=True))
        batch_op.create_index("ix_visits_person", ["person_id"], unique=False)

    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.drop_index("ix_visits_person")
        batch_op.drop_column("person_id")

    with op.batch_alter_table("entry_events", schema=None) as batch_op:
        batch_op.drop_index("ix_entry_events_person")
        batch_op.drop_column("person_id")

    with op.batch_alter_table("active_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_active_sessions_person")
        batch_op.drop_column("person_id")

    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_wallet_transactions_shop")

    op.drop_table("wallet_transactions")
    with op.batch_alter_table("subscription_payments", schema=None) as batch_op:
        batch_op.drop_index("ix_subscription_payments_person")

    op.drop_table("subscription_payments")
    op.drop_table("shops")
    with op.batch_alter_table("person_plates", schema=None) as batch_op:
        batch_op.drop_index("ix_person_plates_plate")
        batch_op.drop_index("ix_person_plates_person")

    op.drop_table("person_plates")
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index("ix_people_shop")
        batch_op.drop_index("ix_people_kind")

    op.drop_table("people")
    with op.batch_alter_table("guest_permits", schema=None) as batch_op:
        batch_op.drop_index("ix_guest_permits_person")

    op.drop_table("guest_permits")
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_index("ix_blocks_plate")
        batch_op.drop_index("ix_blocks_person")

    op.drop_table("blocks")
    with op.batch_alter_table("block_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_block_attempts_block")

    op.drop_table("block_attempts")
    # ### end Alembic commands ###
