"""phase 6 fiscal photos outages

Revision ID: 0005_ops
Revises: 0004_people
Create Date: 2026-09-29 21:09:42.727060
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("outage_events",)


revision = "0005_ops"
down_revision = "0004_people"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fiscal_years",
        sa.Column("name", sa.Unicode(length=40), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("closed_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=True),
        sa.Column("closed_by", sa.String(length=36), nullable=True),
        sa.Column("final_counters", caspian_parking.data.types.JSONText(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fiscal_years")),
        sa.UniqueConstraint("start_date", name=op.f("uq_fiscal_years_start_date")),
    )
    op.create_table(
        "outage_events",
        sa.Column("started_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("ended_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("clean_shutdown", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outage_events")),
    )
    with op.batch_alter_table("outage_events", schema=None) as batch_op:
        batch_op.create_index("ix_outage_events_started", ["started_at_utc"], unique=False)

    op.create_table(
        "photos",
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("path", sa.Unicode(length=400), nullable=False),
        sa.Column("taken_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("keep_forever", sa.Boolean(), nullable=False),
        sa.Column("file_deleted_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index("ix_photos_session", ["session_id"], unique=False)
        batch_op.create_index("ix_photos_taken", ["taken_at_utc"], unique=False)

    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index("ix_photos_taken")
        batch_op.drop_index("ix_photos_session")

    op.drop_table("photos")
    with op.batch_alter_table("outage_events", schema=None) as batch_op:
        batch_op.drop_index("ix_outage_events_started")

    op.drop_table("outage_events")
    op.drop_table("fiscal_years")
    # ### end Alembic commands ###
