"""phase 7 ads coupons raffle

Revision ID: 0006_ads
Revises: 0005_ops
Create Date: 2026-09-29 21:30:28.619372
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("ad_prints", "coupon_redemptions", "raffle_draws")


revision = "0006_ads"
down_revision = "0005_ops"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_prints",
        sa.Column("ad_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_prints")),
    )
    with op.batch_alter_table("ad_prints", schema=None) as batch_op:
        batch_op.create_index("ix_ad_prints_ad", ["ad_id", "created_at_utc"], unique=False)

    op.create_table(
        "ads",
        sa.Column("shop_id", sa.String(length=36), nullable=False),
        sa.Column("package", sa.String(length=20), nullable=False),
        sa.Column("text", sa.UnicodeText(), nullable=False),
        sa.Column("offer", sa.Unicode(length=200), nullable=False),
        sa.Column("location", sa.Unicode(length=120), nullable=False),
        sa.Column("large", sa.Boolean(), nullable=False),
        sa.Column("logo_file", sa.Unicode(length=260), nullable=True),
        sa.Column("on_entry", sa.Boolean(), nullable=False),
        sa.Column("on_exit", sa.Boolean(), nullable=False),
        sa.Column("weekdays", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ads")),
    )
    with op.batch_alter_table("ads", schema=None) as batch_op:
        batch_op.create_index("ix_ads_dates", ["start_date", "end_date"], unique=False)

    op.create_table(
        "coupon_batches",
        sa.Column("shop_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column("template_file", sa.Unicode(length=260), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_batches")),
    )
    with op.batch_alter_table("coupon_batches", schema=None) as batch_op:
        batch_op.create_index("ix_coupon_batches_shop", ["shop_id"], unique=False)

    op.create_table(
        "coupon_redemptions",
        sa.Column("coupon_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("discount", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_redemptions")),
        sa.UniqueConstraint("coupon_id", name=op.f("uq_coupon_redemptions_coupon_id")),
    )
    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.create_index("ix_coupon_redemptions_coupon", ["coupon_id"], unique=False)

    op.create_table(
        "coupons",
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("shop_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("code", name=op.f("uq_coupons_code")),
    )
    with op.batch_alter_table("coupons", schema=None) as batch_op:
        batch_op.create_index("ix_coupons_batch", ["batch_id"], unique=False)

    op.create_table(
        "raffle_draws",
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("sponsor_shop_id", sa.String(length=36), nullable=True),
        sa.Column("candidates", sa.Integer(), nullable=False),
        sa.Column("candidates_digest", sa.String(length=64), nullable=False),
        sa.Column("winner_ticket", sa.String(length=24), nullable=False),
        sa.Column("winner_entry_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raffle_draws")),
    )
    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raffle_draws")
    with op.batch_alter_table("coupons", schema=None) as batch_op:
        batch_op.drop_index("ix_coupons_batch")

    op.drop_table("coupons")
    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.drop_index("ix_coupon_redemptions_coupon")

    op.drop_table("coupon_redemptions")
    with op.batch_alter_table("coupon_batches", schema=None) as batch_op:
        batch_op.drop_index("ix_coupon_batches_shop")

    op.drop_table("coupon_batches")
    with op.batch_alter_table("ads", schema=None) as batch_op:
        batch_op.drop_index("ix_ads_dates")

    op.drop_table("ads")
    with op.batch_alter_table("ad_prints", schema=None) as batch_op:
        batch_op.drop_index("ix_ad_prints_ad")

    op.drop_table("ad_prints")
    # ### end Alembic commands ###
