"""phase 8 camera reads

Revision ID: 0007_camera
Revises: 0006_ads
Create Date: 2026-10-01 15:27:33.716112
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("camera_reads", "plate_corrections", "read_matches")


revision = "0007_camera"
down_revision = "0006_ads"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera_reads",
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("lane", sa.String(length=10), nullable=False),
        sa.Column("camera", sa.Unicode(length=60), nullable=False),
        sa.Column("plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("vehicle_type", sa.String(length=20), nullable=True),
        sa.Column("frames", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_camera_reads")),
    )
    with op.batch_alter_table("camera_reads", schema=None) as batch_op:
        batch_op.create_index("ix_camera_reads_created", ["created_at_utc"], unique=False)
        batch_op.create_index("ix_camera_reads_plate", ["plate_key"], unique=False)

    op.create_table(
        "plate_corrections",
        sa.Column("read_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("read_plate_key", sa.Unicode(length=40), nullable=True),
        sa.Column("corrected_plate_key", sa.Unicode(length=40), nullable=False),
        sa.Column("corrected_vehicle_type", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plate_corrections")),
    )
    with op.batch_alter_table("plate_corrections", schema=None) as batch_op:
        batch_op.create_index("ix_plate_corrections_read", ["read_id"], unique=False)

    op.create_table(
        "read_matches",
        sa.Column("read_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("lane", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_read_matches")),
    )
    with op.batch_alter_table("read_matches", schema=None) as batch_op:
        batch_op.create_index("ix_read_matches_read", ["read_id"], unique=False)
        batch_op.create_index("ix_read_matches_session", ["session_id"], unique=False)

    # ### end Alembic commands ###
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("read_matches", schema=None) as batch_op:
        batch_op.drop_index("ix_read_matches_session")
        batch_op.drop_index("ix_read_matches_read")

    op.drop_table("read_matches")
    with op.batch_alter_table("plate_corrections", schema=None) as batch_op:
        batch_op.drop_index("ix_plate_corrections_read")

    op.drop_table("plate_corrections")
    with op.batch_alter_table("camera_reads", schema=None) as batch_op:
        batch_op.drop_index("ix_camera_reads_plate")
        batch_op.drop_index("ix_camera_reads_created")

    op.drop_table("camera_reads")
    # ### end Alembic commands ###
