"""phase 9 sync

Revision ID: 0008_sync
Revises: 0007_camera
Create Date: 2026-10-01 15:56:56.312363
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("session_aliases", "morning_acks")


revision = "0008_sync"
down_revision = "0007_camera"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "morning_acks",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("passes", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_morning_acks")),
    )
    with op.batch_alter_table("morning_acks", schema=None) as batch_op:
        batch_op.create_index("ix_morning_acks_day", ["day"], unique=False)

    op.create_table(
        "review_items",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("dedupe_key", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("summary", sa.Unicode(length=400), nullable=False),
        sa.Column("refs", caspian_parking.data.types.JSONText(), nullable=False),
        sa.Column("resolution", sa.Unicode(length=400), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_review_items_dedupe_key")),
    )
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.create_index("ix_review_items_status", ["status"], unique=False)

    op.create_table(
        "session_aliases",
        sa.Column("provisional_session_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_aliases")),
    )
    with op.batch_alter_table("session_aliases", schema=None) as batch_op:
        batch_op.create_index("ix_session_aliases_provisional", ["provisional_session_id"], unique=False)
        batch_op.create_index("ix_session_aliases_session", ["session_id"], unique=False)

    op.create_table(
        "shared_secrets",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_shared_secrets")),
    )
    op.create_table(
        "sync_log",
        sa.Column("seq", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(length=60), nullable=False),
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("writer_node", sa.String(length=36), nullable=False),
        sa.Column("logged_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_sync_log")),
    )
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.create_index("ix_sync_log_row", ["table_name", "row_id"], unique=False)

    op.create_table(
        "sync_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("table_name", sa.String(length=60), nullable=False),
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("queued_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_outbox")),
    )
    with op.batch_alter_table("sync_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_sync_outbox_row", ["table_name", "row_id"], unique=False)

    op.create_table(
        "sync_state",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Unicode(length=400), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_sync_state")),
    )
    # plain ADD COLUMN (no table rebuild, so the append-only triggers of camera_reads stay in place)
    op.add_column("camera_reads", sa.Column("after_hours", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # the SQLite table rebuild drops triggers: remove and re-create them around it
    for sql in drop_trigger_sql(dialect, "camera_reads"):
        op.execute(sql)
    if dialect == "mssql":
        op.execute(
            "DECLARE @c sysname = (SELECT name FROM sys.default_constraints WHERE parent_object_id = "
            "OBJECT_ID('camera_reads') AND COL_NAME(parent_object_id, parent_column_id) = 'after_hours'); "
            "IF @c IS NOT NULL EXEC('ALTER TABLE camera_reads DROP CONSTRAINT ' + @c)"
        )
    with op.batch_alter_table("camera_reads", schema=None) as batch_op:
        batch_op.drop_column("after_hours")
    for sql in create_trigger_sql(dialect, "camera_reads"):
        op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("sync_state")
    with op.batch_alter_table("sync_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_outbox_row")

    op.drop_table("sync_outbox")
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_log_row")

    op.drop_table("sync_log")
    op.drop_table("shared_secrets")
    with op.batch_alter_table("session_aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_session_aliases_session")
        batch_op.drop_index("ix_session_aliases_provisional")

    op.drop_table("session_aliases")
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.drop_index("ix_review_items_status")

    op.drop_table("review_items")
    with op.batch_alter_table("morning_acks", schema=None) as batch_op:
        batch_op.drop_index("ix_morning_acks_day")

    op.drop_table("morning_acks")
    # ### end Alembic commands ###
