"""phase 10 hardware

Revision ID: 0009_hardware
Revises: 0008_sync
Create Date: 2026-10-01 16:43:55.754142
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import caspian_parking.data.types
from caspian_parking.data.append_only import create_trigger_sql, drop_trigger_sql

EVENT_TABLES = ("barrier_opens",)


revision = "0009_hardware"
down_revision = "0008_sync"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barrier_opens",
        sa.Column("gate_code", sa.Integer(), nullable=True),
        sa.Column("lane", sa.String(length=10), nullable=False),
        sa.Column("cause", sa.String(length=20), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("reason", sa.Unicode(length=300), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_barrier_opens")),
    )
    with op.batch_alter_table("barrier_opens", schema=None) as batch_op:
        batch_op.create_index("ix_barrier_opens_created", ["created_at_utc"], unique=False)

    op.create_table(
        "person_cards",
        sa.Column("person_id", sa.String(length=36), nullable=False),
        sa.Column("uid", sa.String(length=40), nullable=False),
        sa.Column("label", sa.Unicode(length=60), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("origin_node", sa.String(length=36), nullable=False),
        sa.Column("created_at_utc", caspian_parking.data.types.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_cards")),
        sa.UniqueConstraint("uid", name=op.f("uq_person_cards_uid")),
    )
    with op.batch_alter_table("person_cards", schema=None) as batch_op:
        batch_op.create_index("ix_person_cards_person", ["person_id"], unique=False)

    # ### end Alembic commands ###
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in create_trigger_sql(dialect, table):
            op.execute(sql)


def downgrade() -> None:
    dialect = op.get_bind().dialect.name
    for table in EVENT_TABLES:
        for sql in drop_trigger_sql(dialect, table):
            op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person_cards", schema=None) as batch_op:
        batch_op.drop_index("ix_person_cards_person")

    op.drop_table("person_cards")
    with op.batch_alter_table("barrier_opens", schema=None) as batch_op:
        batch_op.drop_index("ix_barrier_opens_created")

    op.drop_table("barrier_opens")
    # ### end Alembic commands ###
